Develop
EvgeniyaKuzmina/java-explore-with-me pull request #1
Opened 2022-10-26 17:07 UTC by EvgeniyaKuzmina

2022-10-30 15:41 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к Вашей работе. Если будут какие то вопросы приходите ко мне в Slack, по возможности постараюсь на них ответить.

2022-10-30 15:41 UTC, Frilock commented on ewm-service/pom.xml
> +            <version>42.5.0</version>
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х модулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/CategoryRepository.java
> +
Лишняя пустая строчка

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/CategoryRepository.java
> +    // получение списка категорий с пагинацией
Такие комментарии не имеют смысла, по идее по названию метода должно быть понятно, что он делает, если же все таки хотите оставлять такие комментарии, то используйте javadoc - 
/**
*
*/

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/CategoryService.java
> +@Service
Аннотации, которые говорят о том, что класс является бином, нужно ставить над реализацией интерфейса. Над интерфейсами нет смысла в проставлении таких аннотаций

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/CategoryServiceImpl.java
> +
Лишняя пустая строчка в конце метода, проверьте другие места пожалуйста

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/controller/CategoryAdminController.java
> +        log.warn(category.toString());
Предлагаю сделать какой то осмысленный лог, просто вот Вы выведете категорию, и что дальше? Хотя бы нужно указать в логе, какой метод был вызван. Кроме того, по идее toString() можно не указывать, он вызовется и так

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/controller/CategoryPublicController.java
> +@Slf4j
Лишняя аннотация, не вижу использования логгера в данном классе

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/model/Category.java
> +    @Column(name = "id")
Данную аннотацию можно не ставить над идентификатором

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/model/Category.java
> +    @Column(name = "name")
Смотрите, общий комментарий по скрипту и модели данных. Вы когда архитектуру БД планируете, нужно продумать размерность полей, то есть, например, поле код не должно иметь стандартный размер в 255, а его можно сделать, например, в 50 символов, а вот для описание нужно больше места, поэтому логичнее под данную колонку выделить, например, 1000. 
Кроме того, после того как Вы все указали в скрипте, тоже самое нужно сделать в аннотации Column для классов моделей. Указать размерность поля, а также дополнительные флаги, например, nullable = false.

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/client/BaseClient.java
> +        if (response.getStatusCode().is2xxSuccessful()) {
А getStatusCode null вернуть может?

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/CompilationServiceImpl.java
> +        //Collection<Event> events = eventService.getAllEventByIds(compilation.getEvents());
Лучше закомментированный код не оставлять в проекте, через какое то время становится не ясно, для чего он

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/controller/CompilationAdminController.java
> +
Заметил, что вы в конце своих классов оставляете несколько пустых строк, мелочь конечно, но лично я бы посоветовал больше одной не оставлять, это в глаза бросается =)

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/controller/CompilationAdminController.java
> +@Slf4j
Лишняя аннотация

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/controller/CompilationPublicController.java
> +@Slf4j
Лишняя аннотация

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/controller/CompilationPublicController.java
> +        if (pinned == null) {
Мне кажется данное выражение можно заменить на тернарный оператор, будет компактнее

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/mapper/CompilationMapper.java
> +@Slf4j
Лишняя аннотация

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/EventServiceImpl.java
> +
Лишняя строчка в конце метода

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/EventServiceImpl.java
> +        if (event.getState().equals(Status.CANCELED)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее, кроме того не будет NPE.
Вообще не знаю, говорили Вам или нет, но советую установить в IDEA плагин sonarlint - статический анализатор кода, который покажет ряд хороших практик и возможные места с ошибками

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/EventServiceImpl.java
> +        if (event.getEventDate().isBefore(publishedTime.plusHours(2))) {
А event,getEventDate null не вернет?

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/controller/EventAdminController.java
> +    private EventParam creatParam(List<Long> usersId,
Опечатка в слове create

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/controller/EventAdminController.java
> +@Slf4j
Лишняя аннотация, дальше писать о ней не буду, проверьте пожалуйста дальше сами

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/controller/EventPrivateController.java
> +        if (event.getEventDate().isBefore(publishedTime.plusHours(2))) {
Кажется что тут может event.getEventDate() вернуться null и будет NPE, поправьте если не прав

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/dto/EventShortDto.java
> +    @Id
Мне казалось обычно, Id аннотацию используют только в классах моделей, зачем она тут?

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/model/Event.java
> +        return id.equals(event.id) && title.equals(event.title) && description.equals(event.description) && annotation.equals(event.annotation) && initiator.equals(event.initiator) && category.equals
Слишком длинная строчка, давайте сделаем переносы по && символу

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/request/RequestServiceImpl.java
> +        if (event.getRequestModeration().equals(false)) {
Лучше использовать вместо false - Boalean.FALSE

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/request/RequestServiceImpl.java
> +            for (Request r : requests) {
Мне кажется тут не совсем оптимальная структура, вы в цикле делаете запросы на отклонение заявки. А мы разве не можем собрать коллекцию заявок на отклонение и одним запросом им обновить статусы

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/resources/application.properties
> +
Куча лишних пустых строчек в конце файла давайте их уберем

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/main/resources/schema.sql
> +    text      VARCHAR(10000)                          NOT NULL,
Слишком большое поле на мой взгляд,, Postgres поддерживаем такую размерность? Я честно говоря сам запамятовал

2022-10-30 15:41 UTC, Frilock commented on ewm-service/src/test/java/ru/yandex/practicum/mainservice/MainServerApplicationTests.java
> +    void contextLoads() {
Если честно, то хотелось бы от Вас увидеть еще и тесты на Ваши сервисы (unit тесты), знаю, что это задание со звездочкой, но вроде бы у Вас еще есть время. Кроме того, может быть сами какие то неточности отловите

2022-10-30 15:41 UTC, Frilock commented on stats-server/src/main/java/ru/yandex/practicum/statserver/statistic/StatisticMapper.java
> +@Slf4j
Лишняя аннотация

2022-10-30 15:41 UTC, Frilock commented on stats-server/src/main/java/ru/yandex/practicum/statserver/statistic/StatisticRepository.java
> +    @Query("select new ru.yandex.practicum.statserver.statistic.dto.ViewStats(s.app, s.uri, count(distinct s.ip)) " +
А вы не тестировали, ему разве весь путь нужен такой ru.yandex.practicum.statserver.statistic.dto.?

2022-10-30 15:41 UTC, Frilock commented on stats-server/src/main/java/ru/yandex/practicum/statserver/statistic/StatisticServiceImpl.java
> +        if (unique && uris != null)
Хотел бы Вас попросить все таки обособлять данные конструкции даже если они состоят из 1 строчки, дабы защитить себя от ошибок по невнимательности

2022-10-31 16:10 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/CategoryRepository.java
> +
исправлено

2022-10-31 16:11 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/CategoryRepository.java
> +    // получение списка категорий с пагинацией
исправлено

2022-10-31 16:11 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/CategoryService.java
> +@Service
исправлено

2022-10-31 16:11 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/CategoryServiceImpl.java
> +
исправлено

2022-10-31 16:11 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/controller/CategoryAdminController.java
> +        log.warn(category.toString());
исправлено

2022-10-31 16:12 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/category/controller/CategoryPublicController.java
> +@Slf4j
исправлено

2022-10-31 16:13 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/CompilationServiceImpl.java
> +        //Collection<Event> events = eventService.getAllEventByIds(compilation.getEvents());
исправлено

2022-10-31 16:13 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/controller/CompilationAdminController.java
> +
исправлено

2022-10-31 16:14 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/dto/EventShortDto.java
> +    @Id
исправлено

2022-10-31 16:14 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/controller/EventAdminController.java
> +@Slf4j
исправлено

2022-10-31 16:15 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/EventServiceImpl.java
> +
исправлено

2022-10-31 16:15 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/mapper/CompilationMapper.java
> +@Slf4j
исправлено

2022-10-31 16:15 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/controller/CompilationPublicController.java
> +@Slf4j
исправлено

2022-10-31 16:15 UTC, EvgeniyaKuzmina commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/compilation/controller/CompilationAdminController.java
> +@Slf4j
исправлено

2022-11-03 07:12 UTC, Frilock requested changes
Добрый день, почти все мои комментарии поправили, написал еще пару вопросов, и можно будет принимать

2022-11-03 07:12 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/EventServiceImpl.java
> +        if (event.getEventDate().isBefore(publishedTime.plusHours(2))) {
Тут не ответили

2022-11-03 07:12 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/client/BaseClient.java
> +            if (parameters != null) {
Тут тоже по идее можно на тернарное выражение было заменить

2022-11-03 07:12 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/client/EventClient.java
> +@Slf4j
Опять же лишняя аннотация

2022-11-03 07:12 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/client/EventClient.java
> +        Gson gson = new Gson();
А зачем создавать обьект gson на каждый вызов метода? Можно его как поле класса создать по идее

2022-11-03 07:12 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/controller/EventPrivateController.java
> +        if (event.getEventDate().isBefore(publishedTime.plusHours(2))) {
Не ответили на мой комментарий

2022-11-03 07:12 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/dto/NewEventDto.java
> +    @Length(max = 7000)
Вроде обе Length можно в одну уместить, только с 2мя парметрами

2022-11-03 07:12 UTC, Frilock commented on ewm-service/src/main/java/ru/yandex/practicum/mainservice/event/location/Location.java
> +@Table(name = "locations", schema = "public")
public дефолтная схема, ее можно не указывать

2022-11-03 09:58 UTC, Frilock approved these changes
Принято

2022-11-03 11:08 UTC, merged